// lib/db/types.ts — shared types for the database abstraction layer

export interface User {
  id: string;
  username: string;
  createdAt: number;
}

export interface Passkey {
  id: string;
  userId: string;
  credentialId: string;
  publicKey: Uint8Array;
  counter: number;
  deviceType: string;
  backedUp: boolean;
  transports: string | null; // comma-separated list e.g. "internal,hybrid"
  createdAt: number;
}

export interface Challenge {
  id: string;
  challenge: string;
  userId: string | null;
  username: string | null;
  expiresAt: number;
}

export interface Session {
  id: string;
  userId: string;
  expiresAt: number;
}

/**
 * A short-lived token that coordinates cross-device authentication.
 *
 * Pull flow (original): the "requester" device (e.g. phone) creates one and shows
 * a QR code; the "approver" device (already signed in) scans and approves it.
 *
 * Push flow (new): the logged-in device creates a pre-approved token (status already
 * "approved") and embeds the AES localStorage key JWKs so the scanning device can
 * restore the credential encryption keys alongside the session.
 */
export interface CrossDeviceToken {
  id: string;
  /** "pending" → created, waiting for approval; "approved" → approver clicked approve */
  status: "pending" | "approved";
  /** Set when the approver approves — the userId of the approving user. */
  userId: string | null;
  expiresAt: number;
  /** JWK JSON string for the API-key AES encryption key (push flow only). */
  apiKeyJwk: string | null;
  /** JWK JSON string for the credentials AES encryption key (push flow only). */
  credentialsKeyJwk: string | null;
}

/**
 * A persisted record of one local evolve session.
 * In-memory sessions also carry a ChildProcess reference (not stored here).
 */
export interface EvolveSession {
  id: string;
  branch: string;
  worktreePath: string;
  /** One of the LocalSessionStatus values serialised as a string. */
  status: string;
  port: number | null;
  previewUrl: string | null;
  /** The original change request submitted by the user. */
  request: string;
  createdAt: number;
  /** Wall-clock duration of the Claude run in milliseconds (null until complete). */
  durationMs: number | null;
  /** Number of input tokens consumed by the Claude run (null until complete). */
  inputTokens: number | null;
  /** Number of output tokens generated by the Claude run (null until complete). */
  outputTokens: number | null;
  /** Total API cost in USD for the Claude run (null until complete). */
  costUsd: number | null;
}

export interface Role {
  id: string;
  name: string;
  displayName: string;
  description: string;
  createdAt: number;
}

/** This instance's identity and settings. */
export interface InstanceConfig {
  uuid7: string;
  name: string;
  description: string;
  /** The public-facing URL of this instance (e.g. https://primordia.example.com). */
  canonicalUrl: string;
  /** URL of the parent instance to register with (empty string = no parent). */
  parentUrl: string;
}

/** A known peer Primordia instance in the social graph. */
export interface GraphNode {
  uuid7: string;
  /** Current canonical URL, or empty string if unknown. */
  url: string;
  name: string;
  description: string | null;
  registeredAt: number;
}

/** A directed relationship between two instances. */
export interface GraphEdge {
  id: string;
  from: string; // uuid7
  to: string;   // uuid7
  type: string; // e.g. "fork"
  date: string; // ISO date string YYYY-MM-DD
  createdAt: number;
}

export interface UserPreferences {
  userId: string;
  key: string;
  value: string;
  updatedAt: number;
}

export interface DbAdapter {
  // Users
  createUser(user: User): Promise<void>;
  getUserByUsername(username: string): Promise<User | null>;
  getUserById(id: string): Promise<User | null>;
  getAllUsers(): Promise<User[]>;
  getFirstUser(): Promise<User | null>;

  // Passkeys
  savePasskey(passkey: Passkey): Promise<void>;
  getPasskeysByUserId(userId: string): Promise<Passkey[]>;
  getPasskeyByCredentialId(credentialId: string): Promise<Passkey | null>;
  updatePasskeyCounter(credentialId: string, counter: number): Promise<void>;

  // Challenges
  saveChallenge(challenge: Challenge): Promise<void>;
  getChallenge(id: string): Promise<Challenge | null>;
  deleteChallenge(id: string): Promise<void>;
  deleteExpiredChallenges(): Promise<void>;

  // Sessions
  createSession(session: Session): Promise<void>;
  getSession(id: string): Promise<Session | null>;
  deleteSession(id: string): Promise<void>;

  // Cross-device QR tokens
  createCrossDeviceToken(token: CrossDeviceToken): Promise<void>;
  getCrossDeviceToken(id: string): Promise<CrossDeviceToken | null>;
  approveCrossDeviceToken(id: string, userId: string): Promise<void>;
  deleteCrossDeviceToken(id: string): Promise<void>;
  deleteExpiredCrossDeviceTokens(): Promise<void>;
  /** Creates a pre-approved push token that carries optional AES key JWKs for Device B to restore. */
  createCrossDevicePushToken(token: CrossDeviceToken): Promise<void>;

  // Roles (RBAC)
  getAllRoles(): Promise<Role[]>;
  grantRole(userId: string, roleName: string, grantedBy: string): Promise<void>;
  revokeRole(userId: string, roleName: string): Promise<void>;
  getUserRoles(userId: string): Promise<string[]>;
  getUsersWithRole(roleName: string): Promise<string[]>;

  // User preferences (key-value store per user)
  getUserPreferences(userId: string, keys: string[]): Promise<Record<string, string>>;
  setUserPreferences(userId: string, prefs: Record<string, string>): Promise<void>;

  // Instance identity & social graph
  getInstanceConfig(): Promise<InstanceConfig>;
  setInstanceConfig(fields: Partial<Pick<InstanceConfig, "name" | "description" | "canonicalUrl" | "parentUrl">>): Promise<void>;
  getGraphNodes(): Promise<GraphNode[]>;
  upsertGraphNode(node: GraphNode): Promise<void>;
  getGraphEdges(): Promise<GraphEdge[]>;
  upsertGraphEdge(edge: GraphEdge): Promise<void>;

}
