#!/usr/bin/env bash
# scripts/install.sh
# Server-side Primordia setup script.  Run this inside the cloned repo on a VM.
#
# Typically invoked by scripts/install-for-exe-dev.sh, which handles VM
# creation, port setup, and git clone before calling this script.
# Can also be run manually after cloning:
#
#   git clone https://primordia.exe.xyz/api/git ~/primordia
#   cd ~/primordia
#   bash scripts/install.sh

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────

if [[ -t 1 ]]; then
  BOLD="\033[1m"
  GREEN="\033[0;32m"
  CYAN="\033[0;36m"
  YELLOW="\033[0;33m"
  RED="\033[0;31m"
  DIM="\033[2m"
  RESET="\033[0m"
else
  BOLD="" GREEN="" CYAN="" YELLOW="" RED="" DIM="" RESET=""
fi

info()    { echo -e "${CYAN}▸${RESET} $*"; }
success() { echo -e "${GREEN}✓${RESET} $*"; }
warn()    { echo -e "${YELLOW}⚠${RESET} $*"; }
die()     { echo -e "${RED}✗ $*${RESET}" >&2; exit 1; }
diag()    { echo -e "${DIM}  $*${RESET}"; }

# ── ERR trap ──────────────────────────────────────────────────────────────────

_CURRENT_STEP="(initialising)"

trap '_exit_code=$?
echo -e "\n${RED}✗ Install failed${RESET} at step: ${BOLD}${_CURRENT_STEP}${RESET} (line ${LINENO}, exit ${_exit_code})" >&2
echo "" >&2
echo -e "${DIM}  Service logs (last 30 lines):${RESET}" >&2
journalctl -u primordia-proxy -n 30 --no-pager 2>/dev/null >&2 || true
echo "" >&2
echo -e "${DIM}  Service status:${RESET}" >&2
systemctl status primordia-proxy --no-pager 2>/dev/null >&2 || true' ERR

# ── Locate repo root ──────────────────────────────────────────────────────────

_CURRENT_STEP="locate repo root"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REVERSE_PROXY_PORT="${REVERSE_PROXY_PORT:-3000}"

echo ""
echo -e "${BOLD}  Primordia Setup${RESET}"
echo -e "  Repo: ${INSTALL_DIR}"
echo ""

# ── System diagnostics ────────────────────────────────────────────────────────

_CURRENT_STEP="diagnostics"
diag "--- Server diagnostics (paste this if something goes wrong) ---"
diag "Date:      $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
diag "Hostname:  $(hostname -f 2>/dev/null || hostname)"
diag "OS:        $(uname -srm)"
if [[ -f /etc/os-release ]]; then
  diag "Distro:    $(. /etc/os-release && echo "${PRETTY_NAME:-$ID}")"
fi
diag "User:      $(whoami)"
diag "Disk:      $(df -h "${INSTALL_DIR}" 2>/dev/null | awk 'NR==2{print $4" free of "$2}' || echo 'unknown')"
diag "Memory:    $(free -h 2>/dev/null | awk '/^Mem:/{print $7" free of "$2}' || echo 'unknown')"
diag "Repo:      $(git -C "${INSTALL_DIR}" log -1 --oneline 2>/dev/null || echo 'unknown')"
diag "resolv.conf: $(grep -v '^#' /etc/resolv.conf 2>/dev/null | tr '\n' ' ' || echo 'missing')"
diag "DNS scopes:  $(resolvectl status 2>/dev/null | grep 'Current Scopes' | head -3 | tr '\n' ' ' || echo 'n/a')"
diag "--------------------------------------------------------------"
echo ""

# ── Detect exe.dev ────────────────────────────────────────────────────────────

_CURRENT_STEP="detect exe.dev"
HOSTNAME_FQDN="$(hostname -f 2>/dev/null || hostname)"
if [[ "$HOSTNAME_FQDN" == *.exe.xyz ]]; then
  info "Detected exe.dev host: ${HOSTNAME_FQDN}"
  APP_URL="https://${HOSTNAME_FQDN}"
else
  warn "Not running on exe.dev — SSO login and the LLM gateway won't be available."
  APP_URL="http://localhost:${REVERSE_PROXY_PORT}"
fi
echo ""

# ── Install bun ───────────────────────────────────────────────────────────────

_CURRENT_STEP="install bun"
export PATH="$HOME/.bun/bin:$PATH"
if ! command -v bun &>/dev/null; then
  info "Installing bun..."
  curl -fsSL https://bun.sh/install | bash
  export PATH="$HOME/.bun/bin:$PATH"
fi
success "bun $(bun --version)"

# ── Write .env.local ──────────────────────────────────────────────────────────

_CURRENT_STEP="write .env.local"
ENV_FILE="${INSTALL_DIR}/.env.local"
if [[ ! -f "${ENV_FILE}" ]]; then
  cat > "${ENV_FILE}" << EOF
# Generated by Primordia installer — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
REVERSE_PROXY_PORT=${REVERSE_PROXY_PORT}
EOF
  success "Wrote ${ENV_FILE}"
else
  info "Using existing ${ENV_FILE}"
fi

# ── Wait for DNS / outbound internet ─────────────────────────────────────────
# Fresh VMs have a known race: systemd-resolved starts before the NIC is ready,
# leaving DNS broken for up to 120 s.  We detect this and try to fix it before
# running bun install (which would fail with ConnectionRefused on every package).

_CURRENT_STEP="wait for DNS"
_dns_check() { getent hosts registry.npmjs.org >/dev/null 2>&1; }

if ! _dns_check; then
  info "DNS not ready — attempting to fix (systemd-resolved race on fresh VMs)..."

  # Flush stale cache
  sudo resolvectl flush-caches 2>/dev/null || true

  # Restore stub-resolver symlink if missing
  if ! grep -q "127.0.0.53" /etc/resolv.conf 2>/dev/null; then
    sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf 2>/dev/null || true
  fi

  # Restart resolved if it reports no scopes (NIC wasn't ready when it started)
  if resolvectl status 2>/dev/null | grep -q "Current Scopes: none"; then
    diag "Current Scopes: none — restarting systemd-networkd + systemd-resolved"
    sudo systemctl restart systemd-networkd 2>/dev/null || true
    sleep 3
    sudo systemctl restart systemd-resolved 2>/dev/null || true
    sleep 2
  fi

  # Wait up to 60 s for DNS
  _DNS_OK=false
  printf "${CYAN}▸${RESET} Waiting for DNS"
  for _i in $(seq 1 30); do
    if _dns_check; then
      _DNS_OK=true
      break
    fi
    printf "."
    sleep 2
  done
  echo ""

  if [[ "$_DNS_OK" != "true" ]]; then
    warn "DNS still broken — falling back to public DNS (1.1.1.1 / 8.8.8.8)"
    echo -e "nameserver 1.1.1.1\nnameserver 8.8.8.8" | sudo tee /etc/resolv.conf >/dev/null
    sleep 1
  fi
fi

# ── Install dependencies ──────────────────────────────────────────────────────

_CURRENT_STEP="bun install"
info "Installing dependencies (bun install)..."
cd "${INSTALL_DIR}"
_BUN_OK=false
for _attempt in 1 2 3; do
  if bun install --frozen-lockfile; then
    _BUN_OK=true
    break
  fi
  if [[ $_attempt -lt 3 ]]; then
    warn "bun install failed (attempt ${_attempt}/3) — retrying in 15s..."
    sleep 15
  else
    diag "npm registry: $(curl -fsS --max-time 5 https://registry.npmjs.org/ >/dev/null 2>&1 && echo 'reachable' || echo 'UNREACHABLE')"
  fi
done
[[ "$_BUN_OK" == "true" ]] || exit 1
success "Dependencies installed"

# ── Build production bundle ───────────────────────────────────────────────────

_CURRENT_STEP="bun run build"
info "Building production bundle (bun run build)..."
bun run build
success "Build complete"

# ── Install systemd service ───────────────────────────────────────────────────

_CURRENT_STEP="install systemd service"
echo ""
info "Installing systemd service..."
bash "${INSTALL_DIR}/scripts/install-service.sh"

# ── Wait for ready ────────────────────────────────────────────────────────────

_CURRENT_STEP="wait for service ready"
echo ""
info "Waiting for Primordia to be ready (up to 60 s)..."
SERVICE_READY=false
for i in $(seq 1 30); do
  sleep 2
  if journalctl -u primordia-proxy -n 100 --no-pager 2>/dev/null | grep -q "Ready"; then
    SERVICE_READY=true
    echo ""
    success "Primordia is ready!"
    break
  fi
  if [[ $((i % 5)) -eq 0 ]]; then
    info "$((i * 2))s... (journalctl -u primordia-proxy -f to watch)"
  fi
done

if [[ "$SERVICE_READY" != "true" ]]; then
  warn "Service did not report ready within 60 s — it may still be starting."
  echo ""
  echo -e "${DIM}  --- Last 40 lines of service log ---${RESET}"
  journalctl -u primordia-proxy -n 40 --no-pager 2>/dev/null || true
  echo -e "${DIM}  --- Service status ---${RESET}"
  systemctl status primordia-proxy --no-pager 2>/dev/null || true
  echo -e "${DIM}  -------------------------------------${RESET}"
  echo ""
  warn "If the log looks healthy, the service may just need more time."
  warn "Check manually:  journalctl -u primordia-proxy -f"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}${GREEN}  Primordia is running!${RESET}"
echo ""
echo -e "  Open:     ${BOLD}${APP_URL}${RESET}"
echo ""
if [[ "$HOSTNAME_FQDN" == *.exe.xyz ]]; then
  echo -e "  Sign in with your exe.dev account on the login page."
  echo -e "  The first user to sign in is automatically granted the admin role."
  echo -e "  You will be prompted for any missing API keys on first login."
else
  echo -e "  Register a passkey on the login page."
  echo -e "  The first user to register is automatically granted the admin role."
fi
echo ""
echo -e "  Useful commands:"
echo -e "    journalctl -u primordia-proxy -f         # tail proxy logs"
echo -e "    sudo systemctl restart primordia-proxy   # restart"
echo -e "    sudo systemctl stop primordia-proxy      # stop"
echo ""
