// app/api/openapi/route.ts
// Serves the OpenAPI spec, generating it on first request if the file
// doesn't already exist on disk.
//
// public/openapi.json is gitignored and generated by next-openapi-gen.
// This route lets the api-docs page work without any manual build step —
// the spec is produced automatically the first time /api-docs is opened.
//
// next-openapi-gen is run as a child process (same as `bun run generate-api-docs`)
// rather than imported directly, because the package uses `new URL('../../package.json',
// import.meta.url)` which Next.js's bundler can't resolve at build time.

import { existsSync, readFileSync } from 'fs';
import { execFile } from 'child_process';
import { promisify } from 'util';
import path from 'path';

const execFileAsync = promisify(execFile);

const SPEC_PATH = path.join(process.cwd(), 'public', 'openapi.json');

// Module-level promise: all concurrent first-requests share a single generation run.
let genPromise: Promise<string> | null = null;

async function getSpec(): Promise<string> {
  // Fast path: file already exists from a previous request or manual generation.
  if (existsSync(SPEC_PATH)) {
    return readFileSync(SPEC_PATH, 'utf-8');
  }

  // Deduplicate: if generation is already in-flight, wait for that same promise.
  if (!genPromise) {
    genPromise = (async () => {
      // Run next-openapi-gen as a child process so it isn't bundled by Next.js.
      await execFileAsync(
        'bun',
        ['run', 'generate-api-docs'],
        { cwd: process.cwd() },
      );
      return readFileSync(SPEC_PATH, 'utf-8');
    })().finally(() => {
      // Reset so errors are retried on the next request.
      genPromise = null;
    });
  }

  return genPromise;
}

/**
 * @ignore
 */
export async function GET() {
  try {
    const spec = await getSpec();
    return new Response(spec, {
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return new Response(JSON.stringify({ error: `Failed to generate OpenAPI spec: ${msg}` }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}
